WebAPIWithCoreMvc/Models/ErrorViewModel.cs
namespace WebAPIWithCoreMvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebAPIWithCoreMvc/ViewModels/UserAddViewModel.cs
namespace WebAPIWithCoreMvc.ViewModels
{
    public class UserAddViewModel
    {
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public int GenderId { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string Email { get; set; }
        public string Adress { get; set; }
    }
}

WebAPIWithCoreMvc/ViewModels/UserDeleteViewModel.cs
namespace WebAPIWithCoreMvc.ViewModels
{
    public class UserDeleteViewModel
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public int GenderId { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string Email { get; set; }
        public string Adress { get; set; }
    }
}

WebAPIWithCoreMvc/ViewModels/UserUpdateViewModel.cs
namespace WebAPIWithCoreMvc.ViewModels
{
    public class UserUpdateViewModel
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public int GenderId { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string Email { get; set; }
        public string Adress { get; set; }
    }
}

WebAPIWithCoreMvc/Controllers/UsersController.cs
using Entities.Dtos.UserDtos;
using Mapster;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using WebAPIWithCoreMvc.ViewModels;

namespace WebAPIWithCoreMvc.Controllers
{
    public class UsersController : Controller
    {
        #region Defines
        private readonly HttpClient _httpClient;
        private string url = "http://localhost:5065/api/";
        #endregion
        #region Constructor
        public UsersController(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }
        #endregion
        public async Task<IActionResult> Index()
        {
            var users = await _httpClient.GetFromJsonAsync<List<UserDetailDto>>(url + "User/GetList");
            return View(users);
        }
        [HttpGet]
        public IActionResult AddUser()
        {
            ViewBag.GenderList = GenderFill();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddUser(UserAddViewModel userAddViewModel)
        {
            var userAddDto = userAddViewModel.Adapt<UserAddDto>();
            HttpResponseMessage responseMessage = await _httpClient.PostAsJsonAsync(url + "User/Add", userAddDto);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> EditUser(int id)
        {
            var user = await _httpClient.GetFromJsonAsync<UserUpdateDto>(url + "User/GetById/" + id);
            UserUpdateViewModel userUpdateViewModel = user.Adapt<UserUpdateViewModel>();
            ViewBag.GenderList = GenderFill();
            return View(userUpdateViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> EditUser(int userId, UserUpdateViewModel userUpdateViewModel)
        {
            var userUpdateDto = userUpdateViewModel.Adapt<UserUpdateDto>();
            HttpResponseMessage responseMessage = await _httpClient.PutAsJsonAsync(url + "User/Update", userUpdateDto);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            HttpResponseMessage response = await _httpClient.DeleteAsync($"{url}User/Delete/{id}");
            return RedirectToAction("Index");

        }
        private List<Gender> GenderFill()
        {
            List<Gender> genders = new List<Gender>();
            genders.Add(new Gender() { Id = 1, GenderName = "Kadın" });
            genders.Add(new Gender() { Id = 2, GenderName = "Erkek" });
            return genders;
        }
        private class Gender
        {
            public int Id { get; set; }
            public string GenderName { get; set; }
        }
    }
}

WebAPIWithCoreMvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebAPIWithCoreMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAPIWithCoreMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebAPIWithCoreMvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAPIWithCoreMvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebAPIWithCoreMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebAPIWithCoreMvc/Views/Users/AddUser.cshtml
@model WebAPIWithCoreMvc.ViewModels.UserAddViewModel
@{
    ViewData["Title"] = "AddUser";
}

<h1>Kullanıcı</h1>
<div class="row">
    <div class="col-md-4">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <form asp-action="AddUser" method="post">
            <div class="form-group">

                <label asp-for="UserName">Kullanıcı Adı:</label>

                <input asp-for="UserName" class="form-control" />

                <span asp-validation-for="UserName" class="text-danger"></span>

            </div>

            <div class="form-group">

                <label asp-for="FirstName">İsim:</label>

                <input asp-for="FirstName" class="form-control" />

                <span asp-validation-for="FirstName" class="text-danger"></span>

            </div>

            <div class="form-group">

                <label asp-for="LastName">Soyadı:</label>

                <input asp-for="LastName" class="form-control" />

                <span asp-validation-for="LastName" class="text-danger"></span>

            </div>

            <div class="form-group">

                <label asp-for="Password">Şifre:</label>

                <input asp-for="Password" class="form-control" />

                <span asp-validation-for="Password" class="text-danger"></span>

            </div>

            <div class="form-group">

                <label asp-for="DateOfBirth">Doğum Tarihi:</label>

                <input asp-for="DateOfBirth" class="form-control" />

                <span asp-validation-for="DateOfBirth" class="text-danger"></span>

            </div>

            <div class="form-group">

                <label asp-for="GenderId">Cinsiyet:</label>

                <select class="form-control" asp-for="GenderId" asp-items="@(new SelectList

     (@ViewBag.GenderList,"Id","GenderName"))"></select>

                <span asp-validation-for="GenderId" class="text-danger"></span>

            </div>

            <div class="form-group">

                <label asp-for="Email">Email:</label>

                <input asp-for="Email" class="form-control" />

                <span asp-validation-for="Email" class="text-danger"></span>

            </div>

            <div class="form-group">

                <label asp-for="Adress">Adres</label>

                <input asp-for="Adress" class="form-control" />

                <span asp-validation-for="Adress" class="text-danger"></span>

            </div>

            <div class="form-group">

                <input type="submit" value="Ekle" class="btn btn-primary" />

            </div>
        </form>
    </div>
</div>

WebAPIWithCoreMvc/Views/Users/EditUser.cshtml
@model WebAPIWithCoreMvc.ViewModels.UserUpdateViewModel
@{
    ViewData["Title"] = "EditUser";
}

<h1>Düzenleme Sayfası</h1>
<div class="row">
    <div class="col-md-4">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <form asp-action="EditUser" method="post">
            <div class="form-group">

                <label asp-for="UserName">Kullanıcı Adı:</label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName">İsim:</label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName">Soyadı:</label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password">Şifre:</label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth">Doğum Tarihi:</label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GenderId">Cinsiyet:</label>
                <select class="form-control" asp-for="GenderId" asp-items="@(new SelectList
     (@ViewBag.GenderList,"Id","GenderName"))"></select>
                <span asp-validation-for="GenderId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email">Email:</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress">Adres</label>
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Düzenle" class="btn btn-primary" />
                <a class="btn btnalert-info mb-3" asp-action="Index">Listeye geri dön</a>
            </div>
        </form>
    </div>
</div>

WebAPIWithCoreMvc/Views/Users/Index.cshtml
@model IEnumerable<Entities.Dtos.UserDtos.UserDetailDto>
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<h1>Kullanıcılar</h1>

<a class="btn btn-primary mb-3" asp-action="AddUser">Kullanıcı Ekle</a>
<table class="table table-bordered">
    <thead>
        <tr>
            <td>Id</td>
            <td>Kullanıcı Adı</td>
            <td>İsmi</td>
            <td>Soy İsmi</td>
            <td>Cinsiyet</td>
            <td>Doğum Tarihi</td>
            <td>Email</td>
            <td>Adres</td>
            <td>İşlemler</td>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>@item.ID</td>
                <td>@item.UserName</td>
                <td>@item.FirstName</td>
                <td>@item.LastName</td>
                <td>@item.Gender</td>
                <td>@item.DateOfBirth.ToString("dd/MM/yyyy")</td>
                <td>@item.Email</td>
                <td>@item.Adress</td>
                <td>
                    <a asp-action="EditUser" asp-route-id="@item.ID" class="badge badge-info">Düzenle</a>
                    <a asp-action="Delete" asp-route-id="@item.ID" class="badge badge-danger">Sil</a>
                </td>
            </tr>
        }
    </tbody>
</table>